### ISSUE TITLE
Support for dkong (was: "Seems to work with other games")

### ISSUE THREAD

**Issue by mrchrisster** [6t8k/inp2json#1]
Thanks for the script, this is exactly what I was looking for. This is not really an issue, more of a suggestion.
I just replaced "nemesis" with "dkong" and converted my dkong inp file, worked great! Instead of throwing an unsupported message, maybe it could "attempt" to convert?

**Comment by 6t8k** [comment]
Hi, glad you're finding the script useful :)

The ckeck that throws the "Unsupported game" message has a good reason: the input mapping differs between games. As indicated in `README.md`, to add support for another game, it's necessary to look up the corresponding input mapping in the MAME source and add it to `BUTTONS` in line with the existing "nemesis" entry. Otherwise, generally, the output will not be correct - in this particular case, for "nemesis", `JOYSTICK_LEFT` is mapped to `0x01`, while for "dkong", `JOYSTICK_RIGHT` is mapped to `0x01`, so LEFT and RIGHT will be swapped in the output. The mapping for "dkong" is found [here](https://github.com/mamedev/mame/blob/mame0229/src/mame/drivers/dkong.cpp#L950).

In case a game that support is to be added for has identical input mapping to another, already supported game, adding a corresponding tuple to `BUTTONS_ALIAS` is sufficient (as is already done for "gradius"->"nemesis").

**Comment by 6t8k** [comment]
[`b26b213`](https://github.com/6t8k/inp2json/commit/d46dec3e2acb7cd2d57c052ff6a622f1484d24a4) adds support for "dkong".

Prospectively, it would be preferable to make the need to reproduce the input mappings as part of inp2json obsolete by automatically collecting the necessary data from MAME.
